version: '3.5'

services:
  app:
    image: node:18-alpine
    container_name: dpelos-app
    entrypoint: /app/etc/bin/entrypoint.sh
    restart: always
    env_file:
      - ./.env
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
    working_dir: /app
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - node:18-alpine
    volumes:
      - ./:/app
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - dpelosdb
    tty: true

  dpelosdb:
    image: mongo:5.0.0
    container_name: dpelos-database
    ports:
      - "27017:27017"
    volumes:
      - ./mongo:/data/db
